### PR TITLE
Change file names to latest convention

### PR DESCRIPTION
**Pull request by sunarch**
I'm not sure whether leaving earlier files on a different naming convention is intentional, but if not, this updates them to a uniform naming convention base on the latest ones (which is also the best method).

I'm guessing it's possible, for immutable links somewhere or something similar, but haven't seen any.

If it makes sense, then it helps with the ordering in the list view, if not, then sorry for overlooking the reason. :)

### CODE REVIEW

**Comment by erwanvivien** [comment]
@0atman I think this is great, please consider using it

> If it makes sense, then it helps with the ordering in the list view, if not, then sorry for overlooking the reason. :)

Is the main selling point

**Comment by 0atman** [comment]
This is a great plan, thank you very much! I see some conflicts, so I'll just do it manually myself now, as I'm touching the codebase now

**Comment by 0atman** [comment]
Fixed in main!

**Comment by sunarch** [comment]
Glad to help :)

**Pull request closed without merging**
